### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Coder-Jat** [Coder-Jat/hacktoberfest2022#8]
Can someone update readme file according to Hacktoberfest 2022 Including rules and steps

**Comment by mak650650** [comment]
means we have to update  readme file with listing out rule section or anything else

**Comment by Coder-badsara** [comment]
Yes...update readme file by listing hacktoberfest 2022 rules and step to contribute in a customized manner .....
So that it makes an attractive impression on the contributors ...

**Comment by Coder-Jat** [comment]
Yes...update readme file by listing hacktoberfest 2022 rules and step to contribute in a customized manner .....
So that it makes an attractive impression on the contributors ...

**Comment by mak650650** [comment]
assign me
